export enum ProductCategory { ELECTRONICS = 'ELECTRONICS', CLOTHING = 'CLOTHING', BOOKS='BOOKS', FOOD='FOOD', HOME='HOME' }
export enum OrderStatus { PENDING='PENDING', PROCESSING='PROCESSING', SHIPPED='SHIPPED', DELIVERED='DELIVERED', CANCELLED='CANCELLED' }
export enum PaymentMethod { CARD='CARD', CASH='CASH', BANK_TRANSFER='BANK_TRANSFER', DIGITAL_WALLET='DIGITAL_WALLET' }
export enum PaymentStatus { PENDING='PENDING', COMPLETED='COMPLETED', FAILED='FAILED', REFUNDED='REFUNDED' }
